name: Build
on: 
  push:
    branches: main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            json-data-comparator
      
      - name: Build
        run: |
          ls -lrt .
          cd json-data-comparator/www/
          ls -lrt .
          npm run build
          ls -lrt .
